import { useEffect, useState } from 'react'

const blankCampaign = { name: '', keywords: '', location: '', salaryMin: 0, scheduleTime: '09:00', enabled: true, reviewBeforeSubmit: true }
const blankJob = { url: '', title: '', company: '', description: '' }
const blankContact = { name: '', email: '', company: '', role: '', relationship: 'recruiter', notes: '', next_action_at: '' }

export default function Workbench({ active, showToast }) {
  const [campaigns, setCampaigns] = useState([]), [contacts, setContacts] = useState([]), [insights, setInsights] = useState([]), [resumes, setResumes] = useState([])
  const [campaign, setCampaign] = useState(blankCampaign), [job, setJob] = useState(blankJob), [contact, setContact] = useState(blankContact)
  const load = async () => { const [c, p, i, cfg] = await Promise.all([window.api.getCampaigns(), window.api.getContacts(), window.api.getOptimisationInsights(), window.api.getConfig()]); setCampaigns(c || []); setContacts(p || []); setInsights(i || []); setResumes(cfg?.resumes || []) }
  useEffect(() => { if (active) load().catch(err => showToast?.(err.message, 'error')) }, [active])
  if (!active) return null
  const field = (state, setState, key, props = {}) => <input className="input" value={state[key] ?? ''} onChange={e => setState({ ...state, [key]: e.target.value })} {...props} />
  return <div className="page"><div className="page-header"><div><h1>Workbench</h1><p>Campaigns, imported jobs, relationships, and evidence-backed improvements.</p></div></div>
    <div className="stats-grid" style={{ marginBottom: 18 }}>{insights.map((tip, i) => <div className="card" key={i}><div className="stat-label">{tip.kind}</div><h3>{tip.title}</h3><p className="text-muted">{tip.detail}</p></div>)}</div>
    <div className="card" style={{ marginBottom: 18 }}><h2>Search campaigns</h2><p className="text-muted">Each enabled campaign runs weekdays at its own time.</p><div style={{ display: 'grid', gridTemplateColumns: '1.2fr 2fr 1fr 110px 110px', gap: 8 }}>{field(campaign, setCampaign, 'name', { placeholder: 'Campaign name' })}{field(campaign, setCampaign, 'keywords', { placeholder: 'Keywords' })}{field(campaign, setCampaign, 'location', { placeholder: 'Location' })}{field(campaign, setCampaign, 'salaryMin', { type: 'number', min: 0, placeholder: 'Min salary' })}{field(campaign, setCampaign, 'scheduleTime', { type: 'time' })}</div><div style={{ display: 'flex', gap: 18, alignItems: 'center', marginTop: 8 }}><select className="input" value={campaign.resumeId || ''} onChange={e => setCampaign({ ...campaign, resumeId: e.target.value })}><option value="">Default routed resume</option>{resumes.map(r => <option key={r.id} value={r.id}>{r.name || 'Unnamed resume'}</option>)}</select><label><input type="checkbox" checked={campaign.enabled !== false} onChange={e => setCampaign({ ...campaign, enabled: e.target.checked })} /> Enabled</label><label><input type="checkbox" checked={campaign.reviewBeforeSubmit !== false} onChange={e => setCampaign({ ...campaign, reviewBeforeSubmit: e.target.checked })} /> Review before submit</label></div><button className="btn btn-primary" style={{ marginTop: 10 }} onClick={async () => { await window.api.saveCampaign(campaign); setCampaign(blankCampaign); await load(); showToast?.('Campaign saved', 'success') }}>Save campaign</button><div style={{ marginTop: 12 }}>{campaigns.map(c => <div key={c.id} className="list-row" style={{ display: 'flex', gap: 10, alignItems: 'center' }}><strong style={{ flex: 1 }}>{c.name}</strong><span className="text-muted">{c.enabled ? 'Enabled' : 'Paused'} · {c.keywords} · {c.location || 'anywhere'} · {c.scheduleTime}</span><button className="btn btn-ghost" onClick={async () => { await window.api.runCampaign(c.id); showToast?.('Campaign scan queued', 'success') }}>Run</button><button className="btn btn-ghost" onClick={() => setCampaign(c)}>Edit</button><button className="btn btn-ghost" onClick={async () => { await window.api.deleteCampaign(c.id); await load() }}>Delete</button></div>)}</div></div>
    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 18 }}><div className="card"><h2>Import any job</h2><p className="text-muted">Add an unsupported listing to Needs Attention without claiming it was submitted.</p>{field(job, setJob, 'url', { placeholder: 'https://company.example/jobs/…' })}<div style={{ display: 'flex', gap: 8, marginTop: 8 }}>{field(job, setJob, 'title', { placeholder: 'Role' })}{field(job, setJob, 'company', { placeholder: 'Company' })}</div><textarea className="input" style={{ marginTop: 8, minHeight: 90 }} value={job.description} onChange={e => setJob({ ...job, description: e.target.value })} placeholder="Optional description" /><button className="btn btn-primary" style={{ marginTop: 8 }} onClick={async () => { const r = await window.api.importJob(job); if (r?.success === false) return showToast?.(r.reason, 'error'); setJob(blankJob); showToast?.('Job added to Needs Attention', 'success') }}>Import</button></div>
      <div className="card"><h2>Contacts & referrals</h2><div style={{ display: 'flex', gap: 8 }}>{field(contact, setContact, 'name', { placeholder: 'Name' })}{field(contact, setContact, 'email', { type: 'email', placeholder: 'Email' })}</div><div style={{ display: 'flex', gap: 8, marginTop: 8 }}>{field(contact, setContact, 'company', { placeholder: 'Company' })}{field(contact, setContact, 'role', { placeholder: 'Role / context' })}</div><div style={{ display: 'flex', gap: 8, marginTop: 8 }}><select className="input" value={contact.relationship} onChange={e => setContact({ ...contact, relationship: e.target.value })}><option value="recruiter">Recruiter</option><option value="referral">Referral</option><option value="hiring-manager">Hiring manager</option><option value="network">Network</option></select>{field(contact, setContact, 'next_action_at', { type: 'date', title: 'Next action date' })}</div><textarea className="input" style={{ marginTop: 8, minHeight: 70 }} value={contact.notes} onChange={e => setContact({ ...contact, notes: e.target.value })} placeholder="Conversation notes or referral plan" /><button className="btn btn-primary" style={{ marginTop: 8 }} onClick={async () => { const r = await window.api.saveContact(contact); if (!r.success) return showToast?.(r.reason, 'error'); setContact(blankContact); await load() }}>Save contact</button><div style={{ marginTop: 12 }}>{contacts.map(p => <div className="list-row" key={p.id} style={{ display: 'flex', alignItems: 'center', gap: 8 }}><div style={{ flex: 1 }}><strong>{p.name || p.email}</strong><div className="text-muted">{p.relationship} · {p.company} {p.role && `· ${p.role}`} {p.next_action_at && `· next ${p.next_action_at}`}</div></div><button className="btn btn-ghost" onClick={() => setContact(p)}>Edit</button><button className="btn btn-ghost" onClick={async () => { await window.api.deleteContact(p.id); await load() }}>Delete</button></div>)}</div></div></div>
  </div>
}
