const { service, createChecker } = require('./helpers')
const crypto = service('cloudCrypto'), { check, done } = createChecker()
const key = crypto.deriveKey('User@Example.com', 'correct horse battery staple')
const same = crypto.deriveKey(' user@example.com ', 'correct horse battery staple')
check('key derivation is account-stable', key, same)
const encrypted = crypto.encrypt(key, { resume: 'private text', screening: ['yes'] })
check('ciphertext hides the document', encrypted.includes('private text'), false)
check('encrypted payload round-trips', crypto.decrypt(key, encrypted), { resume: 'private text', screening: ['yes'] })
check('wrong key is rejected', (() => { try { crypto.decrypt(crypto.deriveKey('x@y.z', 'wrong'), encrypted); return false } catch { return true } })(), true)
done()
