const fs = require('fs')
const path = require('path')
const crypto = require('crypto')
const { createChecker } = require('./helpers')

const root = path.join(__dirname, '..', '..', 'extension')
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'manifest.json'), 'utf8'))
const popup = fs.readFileSync(path.join(root, 'popup.js'), 'utf8')
const protocolSource = fs.readFileSync(path.join(root, 'protocol.js'), 'utf8')
const protocol = require(path.join(root, 'protocol.js'))
const html = fs.readFileSync(path.join(root, 'popup.html'), 'utf8')
const { check, done } = createChecker()

check('extension uses Manifest V3', manifest.manifest_version, 3)
check('desktop access is optional rather than installed globally', manifest.optional_host_permissions, ['http://*/*'])
check('extension does not request all browsing data', JSON.stringify(manifest).includes('<all_urls>'), false)
check('pairing secret uses session-only storage', popup.includes('chrome.storage.session'), true)
check('pairing secret is not persisted in local storage', popup.includes('chrome.storage.local'), false)
check('imports use signed requests', protocolSource.includes('X-Hiro-Signature'), true)
check('imports use encrypted envelopes', protocolSource.includes('secure: 2'), true)
check('popup has no inline script blocked by MV3 CSP', /<script(?![^>]*src=)/i.test(html), false)
check('extension scripts parse', (() => { try { new Function(protocolSource); new Function(popup); return true } catch { return false } })(), true)

;(async () => {
  const token = 'a'.repeat(64), value = { title: 'Engineer', description: 'Private text' }
  const envelope = await protocol.encrypt(token, value)
  check('extension encryption round-trips with Web Crypto', await protocol.decrypt(token, envelope), value)
  const combined = Buffer.from(envelope.data, 'base64')
  const decipher = crypto.createDecipheriv('aes-256-gcm', crypto.createHash('sha256').update(token).digest(), combined.subarray(0, 12))
  decipher.setAuthTag(combined.subarray(-16))
  const desktopPlain = JSON.parse(Buffer.concat([decipher.update(combined.subarray(12, -16)), decipher.final()]).toString())
  check('extension ciphertext matches the desktop wire format', desktopPlain, value)
  const headers = await protocol.signedHeaders(token, 'POST', '/api/import-job', JSON.stringify(envelope))
  check('extension produces a SHA-256 HMAC signature', /^[0-9a-f]{64}$/.test(headers['X-Hiro-Signature']), true)
  const input = ['POST', '/api/import-job', headers['X-Hiro-Timestamp'], headers['X-Hiro-Nonce'], JSON.stringify(envelope)].join('\n')
  check('extension signature matches the desktop protocol', headers['X-Hiro-Signature'], crypto.createHmac('sha256', token).update(input).digest('hex'))
  done()
})().catch(err => { console.error(err); process.exitCode = 1 })
